config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: %i[create index]

  namespace :admin do
    resources :users
    root to: 'users#index'
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = current_user.articles
  end

  def create
    article = current_user.articles.create(article_params)
    flash[:notice] = 'The article was successfully saved!'
    redirect_to root_path
  end

  private

  def article_params
    params.permit(:title, :description, :url, :url_to_image, )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
require 'google/cloud/translate'

class VisitorsController < ApplicationController
  def index
    @translate = Google::Cloud::Translate.new(
      key: Rails.application.secrets.google_api_key
    )

    newsapi = News.new("6c14c7eb0c254e21b193400d26e8a4e1")
    query = params[:query] || 'south africa'
    @articles = newsapi.get_everything(
      q: query,
      from: 1.week.ago.strftime('%Y-%m-%d'),
      to: Date.today.strftime('%Y-%m-%d'),
      language: 'en',
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @articles.each do |article| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <% if article.url_to_image %>
              <img class="card-img-top" src="<%= article.url_to_image %>" alt="article image">
            <% else %>
              <img class="card-img-top"
                   data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=no-image"
                   alt="article image">
            <% end %>

            <div class="card-body">
              <h5><%= article.title %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'Read', article.url, class: 'btn btn-sm btn-primary' %>
                </div>

                <!-- <small class="text-muted">
                  Published <%#= time_ago_in_words(article.publishedAt) %> ago
                </small> -->
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <!-- <p class="float-right">
      <a href="#">Back to top</a>
    </p> -->
    <p>Project build by William, R. Meunze for IDC Final project</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'My articles', articles_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Admin', '/admin', class: 'nav-link' %></li>

    <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <%= link_to "News Crawler", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <%= render 'layouts/navigation_links' %>
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "News Crawler" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "News Crawler" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3> <u>About the Website</u></h3>

<p>
  This web page is build to host the pages extrated <br>
  by the crawler and published here form more an adequate <br>
  ability to allow users to use and manipulate these as they like.<br>
</p>

<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>

</p>

<p>

   <h4>This web page has been made possible for</h4> <br>
   <h4> <u>IDC PROJECT </u> </h4> <br>
   <h5>done by the student,<h5><br>
    <ul>
    <li>Meunze R.W,</li> <br>
    <li>213142496<br></li>
  </ul>

   <h5><u>Contact</u> <br>
     <br>
 Fill free to contact us for what ever consirning this web page or other inquiry ...
 </h5>
   <ul>
   <li>Contact: 078 231 4575 </li><br>
   <li>Email: roocka19@gmail.com </li><br>
   <li>Address: 4 Burger street </li><br>
   <li>Centurion </li><br>
   <li> 0157 </li><br>
 </ul>

</p>



<p>
  <h4> <%= link_to('join Craft Academy', 'https://www.craftacademy.se/english/') %> </h4> <br>
  12 Week of bootcamp<br>
  Learn to code as a craft<br>
</p>

app/views/shared/_article.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <% if article.urlToImage %>
      <img class="card-img-top" src="<%= article.urlToImage %>" alt="article image">
    <% else %>
      <img class="card-img-top"
           data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=no-image"
           alt="article image">
    <% end %>

    <div class="card-body">
      <% title_st = sanitize translate.translate(article.title || 'no title', to: 'st').text %>
      <% description_st = sanitize translate.translate(article.description || 'no description', to: 'st').text %>

      <h5><%= title_st %></h5>
      <p class="card-text"><%= description_st %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to 'Read', article.url, class: 'btn btn-sm btn-primary' %>

          <%= form_with url: articles_path, local: true do |f| %>
            <%= f.hidden_field :title, value: title_st %>
            <%= f.hidden_field :description, value: description_st %>
            <%= f.hidden_field :url, value: article.url %>
            <%= f.hidden_field :url_to_image, value: article.urlToImage %>
            <%= f.submit 'Save', class: 'btn btn-sm btn-outline-secondary' %>
          <% end %>
        </div>

        <small class="text-muted">
          Published <%= time_ago_in_words(article.publishedAt) %> ago
        </small>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <%= form_with url: root_path, method: :get, local: true do |f| %>
      <div class="input-group mb-3">
        <%= f.text_field :query, class: 'form-control', placeholder: 'What are you in a mood for today? eg: Politics, bitcoin, etc...' %>
        <div class="input-group-append">
          <%= f.submit 'Search', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @articles.each do |article| %>
        <%= render 'shared/article', article: article, translate: @translate %>
      <% end %>
    </div>
  </div>
</div>